name: "CD Pipeline"

on:
    workflow_run:
        workflows: ["Sample React CI Pipeline / Workflow"]
        types:
            - completed
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: production

        steps:

            - name: "Setup nodejs"
              uses: actions/setup-node@v4
              with:
                node-version: '21'

            - name: "Setup vercel cli"
              run: npm install -g vercel

            - name: "Download build files"
              uses: actions/download-artifact@v4
              with:
                name: build
                run-id: ${{ github.event.workflow_run.id }} # this is the run id using this we are able to identify from which workflow it is start downloading artifact
                github-token: ${{ github.token }} #able to access the corresponding repository , without this cd.yml can not able to communicate with ci.yml
            
            - name: "Deploy to vercel"
              run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --confirm --name=cicdproject
          #  Access environemntal secret inside linux maschine
          # {{ secrets.VERCEL_TOKEN }} this is the address where from we are access the token ( readd in the syntax of git actions context tokens syntex)

